ethos_solr:
  image: solr:6.1
  ports:
    - "8983:8983"

#grobid:
#  image: ukwa/grobid
#  ports:
#    - "8080:8080"

#tika:
#  image: logicalspark/docker-tikaserver
#  ports:
#    - "9998:9998"

blacklight:
  build: blacklight
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  environment:
    - SOLR_URL='http://ethos_solr:8983/solr/ethindex'
  ports:
    - "3000:3000"
  links:
    - ethos_solr
